google_plus:
  email: "youremail@example.com"
  password: "1234567890"
  message: "Hey everyone, Let's have some drink to night."
facebook:
  email: "youremail@example.com"
  password: "1234567890"
  message: "Hey everyone, Let's have some drink to night."
